name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  container:
    uses: ./.github/workflows/_container.yml
    with:
      publish: true
    permissions:
      contents: read
      packages: write
